### ISSUE TITLE
Add new CI job with RUBY_MN_THREADS=1

### ISSUE THREAD

**Issue by luke-gru** [ruby-concurrency/concurrent-ruby#1025]
I was looking at the following ruby issue (https://bugs.ruby-lang.org/issues/19996) and thought it could be related to the concurrent-ruby gem, so I ran the tests with RUBY_MN_THREADS=1, and there were some spurious failures. I think some were related to the tests themselves and others were more mysterious to me.

I think it would be helpful to cruby if you ran these tests with this flag, since in the future, ruby will most likely run with this setting on by default.

**Comment by eregon** [comment]
Mmh, I'm not sure how useful it would be, because any failure on such a job and not in regular CI would be a bug of `RUBY_MN_THREADS=1`, not concurrent-ruby. So at least it should not be part of the CI for PRs (AFAIK `RUBY_MN_THREADS=1` is supposed to behave exactly the same as without).
But maybe it could be a daily/weekly job or so.
@ko1 Would that be useful? Or it's enough to run it locally when investigating https://bugs.ruby-lang.org/issues/19996?

It can also be that test failures are just transient errors, in which case they might or not relate to `RUBY_MN_THREADS=1`.

It might also be good to just try it and see, @luke-gru feel free to make a PR or run locally to see if setting that discovers anything interesting.

**Comment by ko1** [comment]
> @ko1 Would that be useful? Or it's enough to run it locally when investigating https://bugs.ruby-lang.org/issues/19996?

It would be helpful after we fix all of failures with MN threads. Now it doesn't have enough quality to check on CI.
(I'm planning to introduce MN enabled CI on ruby/ruby though)

**Comment by luke-gru** [comment]
Makes sense, thanks! I thought it was already checked on cruby's CI but I guess I was wrong.

**Comment by eregon** [comment]
Closing this as there is nothing to do for now, and one can just open a PR after MN is stable enough and passing the test suite.
