### ISSUE TITLE
IO example

### ISSUE THREAD

**Issue by elcuervo** [ruby-concurrency/concurrent-ruby#144]
I know there's some ides in #142 but I'd like to see some examples like `celluloid-io` but using `concurrent-ruby`. Anyone have some or should I just do some?

**Comment by asppsa** [comment]
I've created a simple gem that does IO using the Actors framework [here][io_actors].  Included in the "examples" folder is an example that does "ping pong" over a socket pair.  This isn't really "battle tested" yet -- any feedback on the approach taken is appreciated.

[io_actors]: https://github.com/asppsa/io_actors

**Comment by pitr-ch** [comment]
@asppsa that's great! I did not have time look yet though, I'll do so when I' am back from vacation in a week. Would you consider working with us to create utils for IO cooperation in `concurrent-ruby` gem itself? I would very much like to have some support in `concurrent-ruby` directly.

**Comment by jdantonio** [comment]
@asppsa +1 to what @pitr-ch said. I've take a quick look at your gem and it looks great. We've had a number of requests for better IO-based operations and I'd love to add something of that nature. If you would be interested in possibly implementing some of your work directly in `concurrent-ruby` we'd love to talk more.

**Comment by asppsa** [comment]
Hi guys,

Firstly, I'm very flattered.  In principle I'd be all for getting this
into concurrent-ruby!  I extracted this code out of a closed source
project I am working on with the hope that others could help to improve
the quality of the implementation.  Making it part of your project would
definitely help to advance that goal from what I can see!

The main issue I can see with it at the moment is the dependency on
[nio4r][1], which in MRI/RBX land is essentially a wrapper around libev.
I'm guessing that this hard dependency would have to be removed, as
otherwise people installing CR would have to install libev too, even if
they did not intend to do any IO.  This is easily solved however -- I
can rework the code to probe for nio4r and fall back to `IO#select` when
it is not available (perhaps displaying a warning).

A secondary problem is that there seem to be some garbage collection
issues with the code as-is.  The ping-pong example shows the total
number of actors in memory (and those "alive") growing over time,
whereas it should remain constant.  Because of these problems, I've not
been able to integrate the gem back into the project that it originally
came out of as yet.  From my perspective though this is actually good
reason to get this code included in CR, as it will hopefully mean more
people testing it and submitting patches.  Still, it's worth noting that
the code as-is is a bit wonky.

[1]: https://github.com/celluloid/nio4r

**Comment by asppsa** [comment]
Hi there,

Just thought I'd drop in to say that I've done a bunch more work on my [io_actors][1] gem.  Actually, it uses Agents now instead of Actors and I've added support for multiple "selector" implementations:

* [IO.select][0] (i.e. no external gem required)
* [nio4r][2] (as mentioned, [libev][5]-based in C land)
* [eventmachine][3]
* [ffi-libevent][4] (I made this [libevent][6] wrapper myself, but it's still not really ready to see the light)

The reason for the various back-ends is to take advantage where possible of faster platform specific implementations of [select(3)][7] like epoll and kqueue, which Ruby has no core support for.  I haven't really tested under JRuby at all, but my understanding is that nio4r and eventmachine both have Java-centric things going on there as well.

It's still a work in progress -- the specs all need to be updated for one, and I've only trialled it in the context of socket multiplexing.  I imagine it will need some tweaks if it is to be used for asynchronous file reading, say.

[0]: http://ruby-doc.org/core-2.2.3/IO.html#method-c-select
[1]: https://github.com/asppsa/io_actors
[2]: https://github.com/celluloid/nio4r
[3]: http://rubyeventmachine.com/
[4]: https://github.com/asppsa/ffi-libevent
[5]: http://software.schmorp.de/pkg/libev.html
[6]: http://libevent.org/
[7]: http://manpages.ubuntu.com/manpages/vivid/en/man3/select.3posix.html

**Comment by schmurfy** [comment]
after restarting to work on a project which I want to use concurrent-ruby in I now face this question too, previously I was going for fully evented IO (mainly eventmachine and that is what I use at work) but for simple cases the standard socket classes are a good option too but I am not sure how to implement it.

The problem I have is that on one side I think the server socket should be an actor to be able to be restarted if anything dramatic happens but on the other side having an actor just running an infinite loop seems weird/wrong, is it ? Also even after reading the documentation on Actors about IO I am still not sure how it should be done (the current Actors documentation is really nice btw !)

Here is my current experiment:
```ruby


class UDP < Concurrent::Actor::RestartingContext
  
  def initialize
    super
    self << :start
  end
  
  def on_message(msg)
    if msg == :start
      start()
    end
  end
  
  def start
    @server = UDPSocket.new
    @server.bind('127.0.0.1', 5555)
    
    loop do
      data, address = @server.recvfrom(4096)
      # do something, maybe send the data to another actor
    end
  end
  
  def default_executor
    Concurrent.global_io_executor
  end
  
end

```

**Comment by pitr-ch** [comment]
Sorry for not answering sooner.

@asppsa I am curious why did you switch from actors to agents?

@schmurfy I agree the loop is problematic, it'll block the actor indefinitely. A different pattern can be used here, using the UDP actor as a manager of an internal Thread which will do the loop.
```ruby
require 'set'
class UDP < Concurrent::Actor::RestartingContext

  def initialize
    super
    @thread    = nil
    @listeners = Set.new
  end

  def on_message(msg)
    command, *args = msg
    case command
    when :start
      start
    when :stop
      stop
    when :subscribe
      @listeners.add envelope.sender
    when :unsubscribe
      @listeners.delete envelope.sender
    when :got
      data, address = args
      @listeners.each { |l| l.tell data: data, address: address }
    end
  end

  def start
    @server = UDPSocket.new
    @server.bind('127.0.0.1', 5555)

    @thread = Thread.new(server) do |server|
      while true
        break if server.closed?
        tell [:got, *server.recvfrom(4096)]
      end
    end
  end

  def stop
    # hypothetical API, I am not seure about the actual one
    @server.close
  end

  def default_executor
    # this does not do IO no need for io executor
    Concurrent.global_fast_executor
  end

end
```

**Comment by schmurfy** [comment]
thanks @pitr-ch !
How would you ensure that the thread is destroyed if anything bad happens to the actor ?

**Comment by pitr-ch** [comment]
Closing the server on actor termination event should make the thread leave the loop and end, then it should GC-ed with the actor. It's a rather quick thought, please test. Also the loop should have some exception handling (which I've omitted from the example), something like: sending the error to the actor to let it fail, and terminating the loop.

**Comment by schmurfy** [comment]
thanks I will give it a try.

**Comment by pitr-ch** [comment]
If it works for you, would you be so kind to open a PR to the actor documentation with full example of this?

**Comment by schmurfy** [comment]
yes sure, I will give it a try this week.

**Comment by asppsa** [comment]
Hi @pitr-ch,

Basically, it was the ability agents have to immediately dereference.  This made it much easier to write things like a select loop that lives in a long-running separate thread.  From a high level, the gem still provides a way to allow actors to pass messages over IO ([see here][1]), but the underlying code that manages the reading and writing no longer needs actors (but does instead require agents).

I really need to put in some time to document what I've done, but I'm using it in production now and it seems reliable.  Is there still interest to have this included in CR?  If so, I would be more than happy to undertake whatever work is deemed necessary to allow that to happen.

[1]: https://github.com/asppsa/io_actors/blob/master/lib/io_actors/controller.rb

**Comment by pitr-ch** [comment]
@asppsa thanks, makes sense. BTW There is updated example of IO and actors https://github.com/ruby-concurrency/concurrent-ruby/pull/502#issuecomment-195760049

**Comment by chrisseaton** [comment]
Closing due to extreme age.
