### ISSUE TITLE
Namespaces cleanups

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#261]
go through whole gem and make sure name-spacing is fine everywhere. It will be hard to correct after 1.0 release. One thing comes in mind the name-spacing around atomic reference (result of the gem merge) is little inconsistent, there may be more. Check `Concurrent.methods` for pollution. Hide constants which are not part of public API.

**Comment by pitr-ch** [comment]
Use similar documentation friendly pattern for the different implementations:
```ruby
module Synchronization
    Implementation = case
                     when Concurrent.on_jruby?
                       JavaObject
                     when Concurrent.on_cruby? && (RUBY_VERSION.split('.').map(&:to_i) <=> [1, 9, 3]) <= 0
                       MonitorObject
                     when Concurrent.on_cruby?
                       MutexObject
                     when Concurrent.on_rbx?
                       RbxObject
                     else
                       MutexObject
                     end
    private_constant :Implementation

    class Object < Implementation
    end
  end
```

**Comment by jdantonio** [comment]
The naming of `Atomic` was a [conversation in gitter](https://gitter.im/ruby-concurrency/concurrent-ruby?at=5535d43ffd52de687867e60d) earlier this week. My suggestion from that conversation:

```
We've considered changing the name of Concurrent::Atomic to Concurrent::AtomicReference before the 1.0 release and that's still an open question. We could add an Concurrent::AtomicReference alias in 0.9 and put a deprecation warning to Concurrent::Atomic then remove Concurrent::Atomic in 1.0.
```

**Comment by pitr-ch** [comment]
:+1: for `AtomicReference`

**Comment by jdantonio** [comment]
`AtomicReference` change was merged to master in PR #277.

**Comment by ianks** [comment]
Nice. This was important because it will allow us to differentiate between different types of AtomicReferences (i.e. AtomicMarkableReference, etc.).

**Comment by pitr-ch** [comment]
Current `Concurrent` namespace 
```txt
ls Concurrent
constants:
  AbstractExecutorService            Configuration                  GLOBAL_IO_EXECUTOR         NULL_LOGGER               SemaphoreImplementation
  AbstractStruct                     CONFIGURATION                  GLOBAL_LOGGER              Obligation                SerialExecutorService
  AbstractThreadLocalVar             ConfigurationError             GLOBAL_MONOTONIC_CLOCK     Observable                SerializedExecution
  Async                              CopyOnNotifyObserverSet        GLOBAL_TIMER_SET           PerThreadExecutor         SerializedExecutionDelegator
  AtExit                             CopyOnWriteObserverSet         ImmediateExecutor          PriorityQueue             SettableStruct
  AtExitImplementation               CountDownLatch                 ImmutabilityError          ProcessorCounter          SimpleExecutorService
  Atomic                             CyclicBarrier                  ImmutableStruct            Promise                   SingleThreadExecutor
  AtomicBoolean                      Delay                          IndirectImmediateExecutor  PromiseExecutionError     SingleThreadExecutorImplementation
  AtomicBooleanImplementation        DependencyCounter              InitializationError        PureCountDownLatch        Synchronization
  AtomicDirectUpdate                 Dereferenceable                IVar                       ReadWriteLock             ThreadLocalVar
  AtomicFixnum                       EDGE_VERSION                   LifecycleError             RejectedExecutionError    ThreadLocalVarImplementation
  AtomicFixnumImplementation         EngineDetector                 Logging                    ResourceLimitError        ThreadPoolExecutor
  AtomicNumericCompareAndSetWrapper  Event                          MaxRestartFrequencyError   RubyCachedThreadPool      ThreadPoolExecutorImplementation
  AtomicReference                    Executor                       MultipleAssignmentError    RubyExecutorService       TimeoutError
  CachedThreadPool                   ExecutorService                MutableStruct              RubyFixedThreadPool       TimerSet
  CachedThreadPoolImplementation     FILE_MAP                       MutexAtomicBoolean         RubySingleThreadExecutor  TimerTask
  CAtomicBoolean                     FixedThreadPool                MutexAtomicFixnum          RubyThreadLocalVar        Transaction
  CAtomicFixnum                      FixedThreadPoolImplementation  MutexAtomicReference       RubyThreadPoolExecutor    TVar
  CAtomicReference                   Future                         MutexPriorityQueue         SafeTaskExecutor          VERSION
  ConcurrentUpdateError              GLOBAL_FAST_EXECUTOR           MutexSemaphore             ScheduledTask
  Condition                          GLOBAL_IMMEDIATE_EXECUTOR      MVar                       Semaphore
```
I would like to suggest moving all implementation classes (`Mutex..`, `C...`, etc. ) out of the main space. It's implementation detail anyway. I am not sure how to go about it though. One option would be to move these to `Concurrent::Implementations` namespace. Thoughts?

**Comment by jdantonio** [comment]
I've been giving this a lot of thought and in principle I agree, and I think `Concurrent::Implementation`, `Concurrent::Internal`, or `Concurrent::Core` (or something similar) is fine. My only concern is that this release has gotten *really* big (over 250 commits). I'd like to get this release out the door and begin working on improving the test suite. Since these changes are internal, perhaps we can make this change in 1.0 release?

**Comment by pitr-ch** [comment]
I think it would be better for 0.9, we can postpone it after `pre` thought. We should also re-consider our directory structure. Currently it's not corresponding with the namespaces which is agains usual convention and might be confusing.

**Comment by jdantonio** [comment]
I appreciate that the directory structure is unconventional but we aren't changing it in 1.0. We also aren't creating submodules for most of the public classes. Almost everything that's part of the public API needs to be directly under the `Concurrent` namespace. Creating submodules will be unnecessarily confusing for the users.

The problem for us (and this is a good problem to have) is that we have *so* many abstractions in the public API that placing all those files under `lib/concurrent` is difficult. There would be too many files. That's how the gem was originally structured and it was very confusing. The current directory structure was created based on logical groupings and those groupings still make sense. I appreciate that someone looking at the source code for the first time will have to figure out our groupings, but none of the committers have had a problem so far.

We've struct a good balance between keeping the public API easy to use while also keeping the codebase accessible to those working on it. Being a bit unconventional is a small price to pay.

What I am willing consider is moving some of the "public" class files (such as `fixed_thread_pool.rb`) to `lib/concurrent` and creating submodules for the "internal" files which remain in the existing subdirectories (such as `Concurrent::Executor::RubyFixedThreadPool`). We can also move some of the "internal" files into subdirectories and matching modules (`Concurrent::PriorityQueue` can become `Concurrent::Collection::PriorityQueue`, the mixins can be moved to a `concerns` folder/module, etc.)

The only public groupings that I would be willing to put into submodules are `Actor`, `Channel`, and `Struct` (`Concurrent::ImmutableStruct` becomes `Concurrent::Struct::Immutable`). The first two because they are moving to the Edge gem and the last because it has yet to be released.

The files in the `atomic` folder are staying were they are. There are too many of them to move up in the directory structure. We can consider a `Concurrent::Atomic` submodule in v2.0 but not right now. We've made too many changes in this release already. We don't need to be perfect. People find this gem incredibly valuable despite its rough edges. Right now we need to focus on getting them this code.

I'll work on some reorganization while I'm in Boulder. We'll release what I manage to get done in that time and consider other changes after we've released v1.0.

**Comment by pitr-ch** [comment]
Yep I agree the public classes should stay in `Concurrent::*`. Hm the `Synchronized::Object` should probably move into `Concurrent` as well. I see you point and I think about it in similar way. I would like achieve some order based on clear rules which would fulfill the outlined requirements, but without exceptions. We are before 1.0 and I think now is the right time to align the structure. After 1.0 it won't be possible, or at least we would have to wait until 2.0.

Here is one possible solution:
- any implementation classes can be moved to sub-module to hide since they are implementation detail
- we already adopted the pattern with the main class inheriting from Implementation, we can reuse that to let all the actual implementations and the Implementation constant live grouped in its modules and exposing only the actual main classes.
- I would keep the Structs in main scope not to break the rules
- Only public classes of Actor is Actor::Reference that could be moved to Concurrent and rest hidden.
- Edge stuff (if colliding with current classes) would live under one extra module `Edge` rest wold be in `Concurrent::`

For `Synchronized::Object it would result into:
- `Object < ObjectImplementations::Implementation` in `concurrent/object.rb`
- `ObjectImplementations::Implementation = case ... ` in `concurrent/object_implementations/implementation.rb
- `ObjectImplementations::MutexObject < ObjectImplementations::AbstractObject` in `concurrent/object_implementations/mutex_object.rb
- `ObjectImplementations::MonitorObject < ObjectImplementations::AbstractObject` in `concurrent/object_implementations/monitor_object.rb
- etc.

For atomic references it would be:
- `AtomicReference < AtomicImplementations::AtomicReferenceImplementation` in `concurrent/atomic_reference.rb`
- `AtomicImplementations::AtomicReferenceImplementation = case ...` in `concurrent/atomic_implementations/atomice_reference_implementation.rb`
- `AtomicImplementations::MutexAtomicReference = case ...` in `concurrent/atomic_implementations/mutex_atomice_reference.rb`
- etc.
- `AtomicInteger` and `AtomicBoolean` would share same space `AtomicImplementations`

This particular structure supports following requirements:
- all internal classes live in `...Implementations` namespaces
- `Concurrent::` space is clean, containing only public classes and public API methods on itself
- it is logically grouped
- does not break directory module rule
- current public classes are staying at the same place

I was originally planning to take this issue, so if you would like to look at something more fun I'll gladly do this (whatever we decide to do in the end). You've already done ton of work to get us to 0.9 (me mostly occupied with edge stuff :/).

**Comment by jdantonio** [comment]
I'm comfortable with most of this. It may shake out a little differently as we go through everything (we have a lot of stuff). There is nothing else that I want to work on for 0.9 so I'll work on this. That will give you time to finish up the things you are working on.

Something about `Concurrent::Object` doesn't "feel" right to me. It's more typing, but `Concurrent::SynchronizedObject` is more descriptive and less ambiguous:

```ruby
module Concurrent
  class MyClass < Object # could confuse someone unfamiliar with our code
  end

  class MyOtherClass < SynchronizedObject # unambiguous
  end
end
```

**Comment by pitr-ch** [comment]
yeah You are right :+1: for `Concurrent::SynchronizedObject`.

**Comment by pitr-ch** [comment]
Re-opening not to loose track about this. I would suggest following approach:
- write down the rules for name-spacing
- do a PR silent week before next pre release, where we all cooperate on updating whole gem to follow the writen down rules

**Comment by jdantonio** [comment]
I'm not going to lose track of this. I'm going to work on it today.

**Comment by pitr-ch** [comment]
Sorry, poor choice of words on my behalf, I was reopening just to keep it in the Milestone list. I knew this will not be forgotten.
