### ISSUE TITLE
Moving Actors to core

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#332]

**Comment by jdantonio** [comment]
Now that we are beginning larger discussions about 2.0 I'm going to close out some of these issues. We don't need specific issues for each part of Edge yet. We can make new issues once we have a roadmap.

**Comment by iNecas** [comment]
I don't know where to put write some positive feedback to influence how the 2.0 looks like, but I can say that the actors and futures in the edge are the reason we use concurrent-ruby: we even tried to use IVars for modelling the future values, but it's API was very limiting comparing what's possible in edge.

We also plan on building more on the abstractions that are in the edge right now, so looking forward to have the roadmap clarified here. One thing I wouldn't like to see though is trowing the edge away and trying to solve the things "from scratch". I'm in favor of having the edge to get into shape that could just get into core one day.

I can just give a testimonial here that I'm a happy edge user for long time and when talking about concurrent-ruby to someone, I always make sure to point people to the edge, because it just improves the usability of the gem.

**Comment by jdantonio** [comment]
@iNecas I greatly appreciate the support you've shown, the feedback you've given, and the work you've done to help us grow and prosper. To clarify: we will _not_ be throwing away Edge and starting over. Overall Edge is a fantastic evolution of this library. We absolutely _will_ base 2.0 on the work done in Edge, with most (if not all) of it being retained. We just need to be universally aligned as a team, which we clearly aren't right now. Settling on nomenclature, for example, is a surface issue only and won't affect the core functionality. Similarly, consistency in how we handle internal construction (such as `autoload` vs. `require`) won't affect the core functionality. Moving Edge features to core in a deliberate and controlled manner (versus slamming everything in at once without proper discussion and alignment) won't effect the core functionality. But taking the time to do all these things right--rather than acting prematurely on impulse and raw desire--will be of vastly more benefit to the entire user base. If we are to be successful with the migration from 1.0 to the very different 2.0 we _must_ put [user experience first](https://github.com/ruby-concurrency/concurrent-ruby/issues/541).

**Comment by jdantonio** [comment]
@iNecas Also, please see issue #541, #542, and subsequent issues for further discussion. But please continue to post on whichever PRs or Issues are most relevant to you, even when they are closed. Your feedback is important.

**Comment by iNecas** [comment]
Thanks @jdantonio for explanation. I've seen both issues already, and they make a ton of sense, but were to abstract for me to see how it translates to actual steps. That's why I appreciate your comment here. I will watch the subsequent issues and will try to participate if I have something to say to given topic.
