### ISSUE TITLE
Subset require is not working

### ISSUE THREAD

**Issue by dsnipe** [ruby-concurrency/concurrent-ruby#402]
Hello. 
In my project I need only `Promise` component. I try to require only it as described in readme: 
`require 'concurrent/promise'`
But when I tried to run an application, I get: 
`delay.rb:159:in 'ns_initialize': uninitialized constant Concurrent::Delay::Executor (NameError)`
If i required the whole `concurrent`, everything works perfect (amazing gem, btw :+1: )

**Comment by jdantonio** [comment]
Thanks for letting me know. I've removed that section of the README. As the gem has grown we've begun having circular-reference issues with the global configuration and some of the high-level abstractions like `Promise` (see #388). The gem loads very quickly because we don't initiate any back-end services nor do we do much metaprogramming (both requirements of Rails dependencies and we're a runtime dependency in Rails 5) so there isn't much to gain from loading slivers of the gem. Hopefully a full-require of the gem is OK for you.

In the 2.0 release we'll be consolidating many of the high-level abstractions (Future, Promise, others) in a way that should enable limited requires again.
