### ISSUE TITLE
clarify plans for Java <8 support?

### ISSUE THREAD

**Issue by jrochkind** [ruby-concurrency/concurrent-ruby#435]
The README currently says:

> Java 8 is preferred for JRuby but every Java version on which JRuby 9000 runs will be supported.

However, loading concurrent-ruby 0.9.1 under Java 7 produces a deprecation warning that Java 7 will _not_ be supported in 1.0 release:

> WARN -- Concurrent: [DEPRECATED] Java 7 is deprecated, please use Java 8.
> Java 7 support is only best effort, it may not work. It will be removed in next release (1.0).

Which message represents current intentions/plans?  Will Java 7 support be removed, or will it be retained as long as JRuby 9k runs on it, even if Java 8 is preferred?

Can the two messages be made consistent, in either direction?

**Comment by jdantonio** [comment]
Java 7 **will** be supported in concurrent-ruby 1.0.

Originally we planned to drop support for Java 7 but we've reversed direction on that. Now that Rails 5 uses concurrency-ruby (we're a dependency in ActiveSupport) we need to support whatever platforms Rails supports. Rails supports JRuby 9000 on any version of Java that JRuby 9000 supports. That means both Java 7 and Java 8. Se we've committed to supporting Java 7.

The only issue with Java 7 is in the synchronization layer. Java 7 makes weaker concurrency guarantees than Java 8 (although they are still *very* strong). We can't provide guarantees that the runtime can't support, but we are trying to make the strongest possible guarantees that we can, while still being consistent on all platforms. We currently make the strongest guarantees of any Ruby concurrency library, so we're getting to very deep internals here. The different between Java 7 and 8 in this specific instance is at such a deep level that you would have to be working extra hard to write the most efficient concurrent code possible. 99.999% of the time it's not an issue at all.

**Comment by jrochkind** [comment]
Awesome. 

So the deprecation notice should be eliminated or changed in the next minor or patch release? It should either be eliminted entirely for Java 7, or just say that Java 8 is preferred but without saying Java 7 support will be removed?

If you think the Java 7 problems aren't likely to effect most people, I'd suggest removing the deprecation warning entirely. It's annoying to have it in your logs every time you start your app, and disconcerting to someone who may have concurrent-ruby as an indirect dependency and not be working with it directly themselves, and shoudln't need to have to spend the time to figure out what's up with it, if Java 7 is really fine.

**Comment by jrochkind** [comment]
Also, that's awesome to hear Rails 5 will have a dependency on concurrent-ruby. Sweet. 

I _really hope_ that concurrent-ruby can get a 1.0 release, with full semver commitment, before Rails 5 drops.  Rails does already have a variety of dependencies on pre-1.0 gems... but it makes things confusing and overly complicated.  Semver suggests if your gem is already being used widely in production it _really really_ should already be at 1.0, which is violated by a variety of pre-1.0 releases that already released Rails versions have as direct or indirect dependencies. It's un-fun to deal with.

**Comment by jdantonio** [comment]
You made your second post just as I was about to post my response to your first.

To your first post: Very good point. I wasn't planning any more 0.9.x releases since we've had several 1.x pre-releases, but if that warning is causing confusion we should address that. I'll create a new patch release of 0.9 this weekend that changes or removes the warning.

To your second: The 1.0 release will be out before RubyConf in November or Rails 5 drops, whichever comes first (my bet is on RubyConf). Rails depends on 1.0.0.pre3, with a Gemfile reference to our master branch so that they always have the latest version. Rails cannot use 0.9.x because it depends on features we added in 1.0.

All we're really working on right now is documentation and improvements to our test suite, plus some Edge gem stuff. We could release 1.0 tomorrow if we wanted. We're just taking advantage of the extra time while we have it. I had originally wanted it out earlier this summer but a few things became more involved than we expected. The side effect of this is that we put a lot more in 1.0.

**Comment by jrochkind** [comment]
:yellow_heart:

**Comment by jrochkind** [comment]
This project is _so awesome_, thank you guys!!

**Comment by jdantonio** [comment]
Addressed in PR #440

**Comment by jdantonio** [comment]
0.9.2 has been released along with Edge 0.1.2.
