### ISSUE TITLE
NameError: uninitialized constant Concurrent::Future::Options

### ISSUE THREAD

**Issue by tarcieri** [ruby-concurrency/concurrent-ruby#480]
Involved gem versions can be inferred from the backtrace. JRuby 9.0.4.0.

```
NameError: uninitialized constant Concurrent::Future::Options
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/future.rb:134:in `ns_initialize'
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/ivar.rb:66:in `block in initialize'
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/ivar.rb:66:in `synchronize'
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/ivar.rb:66:in `initialize'
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/future.rb:32:in `initialize'
/project/vendor/bundle/jruby/2.2.0/gems/concurrent-ruby-1.0.0-java/lib/concurrent/future.rb:75:in `execute'
/project/vendor/bundle/jruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/manifest.rb:192:in `block in compile'
```

**Comment by tarcieri** [comment]
This occurs when sprockets is precompiling assets as part of a standard Rails workflow

**Comment by atambo** [comment]
Hitting this on jruby 1.7.23 as well :(

**Comment by jdantonio** [comment]
This is a problem with an autoload call behaving differently on JRuby than MRI. The `manifest.rb` file in sprockets calls `require 'concurrent/future'` rather than the recommended `require 'concurrent'`. I've opened an [issue with sprockets](https://github.com/rails/sprockets/issues/199). I'll keep working on it from my end and see if I can find a solution. In the interim, please try adding `require 'concurrent'` in your Rakefile and see if that clears the error for now.

// @schneems @headius

**Comment by jdantonio** [comment]
Possible fix in PR #481

**Comment by cavpollo** [comment]
Adding <code>require 'concurrent'</code> in the Rakefile fixed temporarly the issue, thanks

**Comment by jdantonio** [comment]
@cavpollo Thank you for testing this.

I am out of town on business but will be home soon. Once I get home I'll add a bunch of tests like the ones suggested by @schneems then issue a 1.0.1 release with this update. That should be done sometime next week.

**Comment by jdantonio** [comment]
#481 merged.
