### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by balasankarc** [ruby-concurrency/concurrent-ruby#484]
Hi,
I am packaging concurrent-ruby for Debian as part of GitLab packaging and am stuck with a weird test failure. All the tests run fine except one. The log can be seen here - http://paste.debian.net/343198/

Please help me fix it.

**Comment by jdantonio** [comment]
That test is not part of the core concurrent-ruby gem, it's part of the Edge gem and can safely be ignored. The code under test won't be packaged with concurrent-ruby.

We build three gems out of this repository:

* concurrent-ruby is the core gem
* concurrent-ruby-ext contains optional C extensions
* concurrent-ruby-edge contains experimental features not necessarily ready of inclusion in the core gem

The code being tested by the failing test is part of concurrent-ruby-edge. If you package just the core concurrent-ruby gem you won't have that code.

I'm out of town for business today but will be home soon. Once I return home I'll go through our tests and make sure that all tests *not* in the core gem are tagged so that they can be easily excluded from CI runs.

To see what files are in which gem please reference our [file map](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/support/file_map.rb).

**Comment by balasankarc** [comment]
Ok. Thanks. I will skip it in the package for now.

**Comment by balasankarc** [comment]
@jdantonio Hi, when you get time, can you please tag which all tests are part of the core gem?

**Comment by jdantonio** [comment]
Tomorrow is Christmas Eve so I won't be able to get to this for a few days. I hope to be able to do this next week.

**Comment by balasankarc** [comment]
That is fine. For now I will simply disable the failing tests. Happy holidays. :)

**Comment by jdantonio** [comment]
Merged in PR #491.

**Comment by balasankarc** [comment]
Thanks @jdantonio . This is a great help.
