### ISSUE TITLE
DEFAULT_MAX_POOL_SIZE is too high on non-JRuby

### ISSUE THREAD

**Issue by FooBarWidget** [ruby-concurrency/concurrent-ruby#485]
On non-JRUBY, `DEFAULT_MAX_POOL_SIZE` is set to about 2 billion. This is way too high: MRI can't spawn that many threads, the OS will return an error way before that limit is reached.  `Concurrent.global_io_executor` has `max_threads` set to this value. I thought I could just put thousands of I/O operations in that thread pool and wait for it to finish, but the thread pool errors out with a thread creation error because the maximum is too high.

I suggest lowering `DEFAULT_MAX_POOL_SIZE` to a saner value, like 2048. I also suggest lowering the maximum for `global_io_executor`.

**Comment by jdantonio** [comment]
Configuration of the global thread pool is something we've discussed extensively in the past. We believe the current settings are the best settings for the general audience. All of our high level abstractions support thread pool customization via dependency injection. When the current settings don't support a specific use case we recommend that users configure their own thread pool (explained below).

The problem with global configuration is determining a value that is "sane" for all users. Generally, that's an impossible task. The number of threads that can be supported at any given time is not controlled by Ruby, it's a function of the operating system. On all major Ruby runtimes (MRI, JRuby, and Rbx) each instance of `Thread` maps directly to an operating system thread. Different operating systems handle threads differently so it is impossible for us to predict a "reasonable" maximum. OS X, for example, can only support around 2000 threads for *all* running applications. I've never been able to create more than about 1500 from a single program on OS X, and the max is never consistent. Conversely I've been able to create many thousand threads on some versions of Linux--I've never actually reached a maximum.

Setting the max value too high, it turns out, as actually *less* risky that setting it to low. This is why thread pools in `java.util.concurrent` have a maximum size of `Integer::MAX_VALUE` (which is where we got the the number 2,147,483,647).

Let's say, for example, that I set the max value to 1024. Based on my experience this is a reasonable max that will succeed most of the time on OS X (I've never gotten anywhere close to the 2048 you suggest). For some users we will artificially and unnecessarily throttle their applications. Some users may be on an operating system that can support far more threads than that and we'll force them to use a less than optimal number of threads. The problem with this scenario is that this throttling will be opaque to the user--they will have no way of knowing that their application is experiencing suboptimal performance.

By setting the maximum thread value to a ridiculously high number, as `java.util.concurrent` does, we create a *transparent* failure. I appreciate the frustration you may have felt when your application raised an exception, but you *knew* what the problem was. This transparency gave you the opportunity to take action and optimize your application appropriately for your specific platform and needs.

In extreme cases such as yours the best practice is to configure your own thread pool then use dependency injection to explicitly set the thread pool on which your tasks run. Most abstractions support a `:executor` option (`Future`, `Promise`, `Actor`, others). Other abstractions provide specific methods for injecting the thread pool (such as `Agent#send_via`). These options allow for very fine grained thread pool optimization. For example:

```ruby
threadpool = Concurrent::ThreadPoolExecutor.new(
  max_threads: 1024,
  min_threads: 100,
  max_queue: 2_147_483_647
)

1_000_000.times do
  Concurrent::Future.execute(executor: threadpool) do
    do_something_very_important
  end
end
```

In this example, all the `Future` objects created in the loop will post their tasks to the given thread pool instead of the global thread pool. Even better, this approach will allow for per-platform and even user-controlled configuration (`max_threads` could be set based on a value from `ENV`, and config file, etc.).

**Comment by FooBarWidget** [comment]
You raise a good point w.r.t. transparency of failure. Maybe link to this discussion from the documentation for `global_io_executor`?

**Comment by pitr-ch** [comment]
@jdantonio great explanation! :+1: for linking or adding to the documentation. Better solution might be instead of creating more thread via custom thread pools (which brings burden of managing their live time) to implement some throttling tool limiting certain kind of operations to 1024 but running them still on the global pool with rest of the operations. This is something we should explore for 2.0.
