### ISSUE TITLE
Potentially wrong documentation for Concurrent::Future state

### ISSUE THREAD

**Issue by ristovskiv** [ruby-concurrency/concurrent-ruby#523]
I was having a discussion with @chrisseaton on gitter chat about one simple sample of code that I used for practicing and learning the abstractions of concurrent-ruby. Here is my code

```
count = Concurrent::Future.execute{ sleep(10); "Testing..." }
100.times do |i|
  if count.pending?
    puts i
  else
    count.value
  end
end

```
So I was expecting an output of numbers from 0 to 99 but I only got 0 and 1. And when I've printed out the state of the Future object with

```
100.times do |i|
  puts i
  puts future.state
end 
```

The first time I get state of `pending` and then it is `processing`, but in the docs it doesn't show anywhere a state of `processing`. Even there is a sentence that says `"Once the #execute method is called the state becomes :pending and will remain in that state until processing is complete."`

**Comment by jdantonio** [comment]
Thank you for pointing this out. The documentation is incorrect and your code is behaving as expected. When I added the `: processing ` state I apparently forgot to update the docs. I'll fix that.

Originally there was no `: processing ` state. The statement "becomes :pending and will remain in that state until processing is complete" is exactly how it worked. But then I added the `#cancel` method.

One of the most frequent feature requests we receive is to cancel long-running tasks. I have always steadfastly refused to do this. The only way we can cancel long-running tasks at the library level is to kill the thread on which the task is running. I won't do this. We have no way of knowing what resources the job has open or what state the application is in while a job is being processed. Killing a thread will have unpredictable results. Canceling long-running jobs can only safely be done at the application level and only then by careful design. So I leave that task to the application developer.

During one such discussion it was noted that it would be safe to cancel a job *before it begins processing*. Jobs post to thread pools may go into a queue before they are picked up by a thread. It just depends on how the thread pool is configured, the load at the time, etc. Since all our high-level abstractions like `Concurrent::Future` post to thread pools, we realized that a limited `#cancel` method was possible. Such a method would cancel a job that was queued to a thread pool but not yet claimed by a thread. To implement such a feature I needed to be able to distinguish between a job that was on a queue and a job that was actively being processed by a thread. And that's where the `:processing` state comes from.

Once a job is pulled from the queue by a thread and that thread begins processing it, the state is set to `:processing`. A `:processing` job is considered `:incomplete`. Since most algorithms check `#complete?` or `#incomplete?` the change was relatively innocuous (note how long it took for us to discover that the documentation is wrong). In your example you put the thread to sleep for 10 seconds. The job is pulled from the queue, the state is set to `:processing`, the thread goes to sleep, then you call `#pending?` which correctly returns false.

If you change `if count.pending?` to `if count.incomplete?` it will behave the way you intended.

**Comment by ristovskiv** [comment]
Wow, what a thorough explanation. Thanks, really, and I'm very glad to assist you guys in any way. I was trying to figure out how the Ruby GIL works and what is his role and I ran into your talk on RailsConf 2015 which was amazing. I've found this library there, but I simply can't find any tutorials or books except the documentation (and the gitter chat which the response time was instant even though it was a beginners question). I know that the gems intention is not introduction to the concept of threading, but if it's Rails and Sidekiq's dependency this is something big and could probably teach us how to properly multi-thread with Ruby and use it in Rails, Sinatra or other Ruby projects.

**Comment by jdantonio** [comment]
I'm glad you found my GIL talk informative. Thank you! Making concurrency accessible to all Ruby programmers has always been a goal of this gem--and frequently that means helping to educate the community.

I've updated the docs in #524. Please let me know if it makes sense.

**Comment by ristovskiv** [comment]
Sorry about writing replying this late, I've had some personal problems. Anyway now it seems that everything is fine.

**Comment by jdantonio** [comment]
I'm sorry to hear about you personal problems. Hopefully things are getting better. Thanks again for taking the time to help us make this library better!
