### ISSUE TITLE
Concurrent::RejectedExecutionError under certain conditions (JRuby etc)

### ISSUE THREAD

**Issue by perlun** [ruby-concurrency/concurrent-ruby#527]
We have been seeing &lt;title&gt; now a bit in our environment. But only on _one_ of the servers, strangely enough. There are three of them, with the same config and the same version of the app running.

We are using JRuby, 1.7.22 at the moment. The code is quite simple, something like this (edited for the GH issue):

```ruby
require 'concurrent'

module MyApp
  class Store
    # Would like to 'include Concurrent::Async', but it causes infinite recursion errors.
    def initialize(request, monitor, db)
      # Must exist: http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Async.html
      super()

      @request = request
      @monitor = monitor
      @db = db
    end
  end

  class M3ApiStore < Store
    def initialize(request, monitor, m3_api_caller, db)
      super(request, monitor, db)

      @m3_api_caller = m3_api_caller
    end
  end

  module Stores
    class ComponentsStore < M3ApiStore
      include Concurrent::Async

      def find_by(item_number)
        @item_number = item_number

        find_by_helper
      end
```

The `ComponentStore#find_by` is then called asynchronously, which is when the error occurs.

**Note**: I'm not 100% sure that this class is what triggered the error; we have a bunch of similar classes which are called in an async way, in parallel:

```ruby
def add_extra_data(product)
  item_number = product.fetch(:itemNumber).strip

  components_handle = components_store.async.find_by(item_number)
  configuration_handle = configuration_store.async.find_by(item_number)
  item_warehouse_handle = item_warehouse_store.async.find_by(item_number)
  supplier_handle = supplier_store.async.find_by(product.delete(:supplierNumber))
  warehouse_balances_handle = warehouse_balances_store.async.find_by(item_number)

  product[:components] = components_handle.value!(TIMEOUT)
  product[:configuration] = configuration_handle.value!(TIMEOUT)
  product[:itemWarehouse] = item_warehouse_handle.value!(TIMEOUT)
  product[:supplier] = supplier_handle.value!(TIMEOUT)
  product[:warehouseBalances] = warehouse_balances_handle.value!(TIMEOUT)
end
```

Restarting the application server "solved" the problem this time, but we're fairly confident that it will happen again. Any suggestions or ideas about where to start digging if/when it comes back?

/cc @matias-enroth-ecraft

**Comment by jdantonio** [comment]
@perlun I apologize for the late response. I was out of town attending a conference when you post your issue.

Honestly, I have no idea why you are experiencing this. `Concurrent::Async` uses one of the global thread pools, which is configured with "unlimited" [maximum queue size](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/configuration.rb#L142). On JRuby it isn't strictly unlimited because `java.util.concurrent` won't allow for an unlimited queue, but the max is a [very big number](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/executor/java_thread_pool_executor.rb#L13). The two main reasons you should see job rejected are 1) exceeded maximum queue size and 2) the OS refuses to allocate more threads. Both are generally very unlikely. OS X can only handle around 2000 threads for all applications before it starts refusing to create more threads, but I've been able to reliably get 1100-1200 for a single app during testing. In Linux I've never been able to hit the maximum number of threads. Maybe the JVM has its own max threads? Even so, you would have to generate a ton of threads and that's unlikely if your async jobs are doing IO. And to happen on only one server is fairly odd, too.

**Comment by jdantonio** [comment]
When running on JRuby our thread pools are light wrappers around `java.util.concurrent.ThreadPoolExecutor`. So everything in [those docs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html) apply here. The error your are seeing is the result of us setting `ThreadPoolExecutor.AbortPolicy`.

**Comment by jdantonio** [comment]
@perlun @matias-enroth-ecraft Have you made any progress on this?

**Comment by perlun** [comment]
@jdantonio - sorry for the lack of feedback. We have not seen this since that single occurrence. It is likely a bug _somewhere_ (either in our app code, the gem, in JRuby, the JVM, etc...) but it doesn't seem to appear very often.

Let's keep this closed for now, I'll ping this GitHub issue once again if we reproduce it again.
