### ISSUE TITLE
Future's observers are run on the same executor as the future

### ISSUE THREAD

**Issue by bsedat** [ruby-concurrency/concurrent-ruby#532]
The [Future documentation](http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Future.html) section about observers states that "The notification will occur on the global thread pool.". I've noticed that if a different executor is specified for the Future then it runs the Observers on that same executor as well. Is it an omission from the docs that observers also run on the same executor?

I've illustrated this with some code below:
```ruby
thread_pool = Concurrent::FixedThreadPool.new(1)
class ObserverTime
  def update(*args)
    sleep 10
    puts "Observer time: #{Time.now}"
  end
end
3.times do
  f = Concurrent::Future.new(executor: thread_pool) { puts Time.now }
  f.add_observer(ObserverTime.new)
  f.execute
  f.wait
  puts "Set done. #{Time.now}"
end
```
that prints:
```
2016-05-05 16:40:55 -0700
Set done. 2016-05-05 16:40:55 -0700
Observer time: 2016-05-05 16:41:05 -0700
2016-05-05 16:41:05 -0700
Set done. 2016-05-05 16:41:05 -0700
Observer time: 2016-05-05 16:41:15 -0700
2016-05-05 16:41:15 -0700
Set done. 2016-05-05 16:41:15 -0700
```

**Comment by jdantonio** [comment]
Good catch. Thank you for pointing this out! The docs are wrong, the behavior is as intended.

The intent is for the observation to occur on the thread that processed the job. This allows us to make guarantees regarding execution order with respect to the job and its observers.

In the earliest versions of the gem (future ID on of the earliest abstractions I wrote) there was no dependency injection for executors. We didn't even have the concept of "executor." Just a global thread pool which could be configured during gem initializion. Since we only had one thread pool, the global thread pool, the doc as written was correct. Apparently I never updated this section of the docs.

**Comment by bsedat** [comment]
Makes sense. I wanted to double-check what was going on/intended :smile:. Loving the library so far!

**Comment by jdantonio** [comment]
Docs updated in commit 0d044bebdda2781b1b265472555090941232bbe5.
