### ISSUE TITLE
Strange interaction between local variables and Concurrent::Array; warn about += usages

### ISSUE THREAD

**Issue by vemv** [ruby-concurrency/concurrent-ruby#570]
Hi there!

I found a strange case I have no explanation for. Perhaps it's familar to you.

There's a workload which I partition by months (groups of 30 days), having one thread to process each month.

The code looks like this:

``` ruby
from = Date.new(2016, 1, 1)
to = Date.today

transactions = Concurrent::Array.new
threads = Concurrent::Array.new

(from..to).to_a.in_groups_of(30, false).map do |dates|
  threads << Thread.new do
    v = get_transactions(dates.min, dates.max)
    transactions += v
  end
end

threads.each(&:join)
```

(in this code a 'transaction' simply means a business transaction, like a purchase)

The thing is that if I tried the following change:

``` diff
- v = get_transactions(dates.min, dates.max)
- transactions += v
+ transactions += get_transactions(dates.min, dates.max)
```

I would get totally different results. Which is really surprising for semantically identical code.

I can consistently reproduce the issue; however I cannot share a private project.

Can you give me any pointer?

Cheers - Victor

**Comment by chrisseaton** [comment]
Is `v` defined somewhere else in this code, outside of the block? Perhaps the `v` is being used by all threads? If it is then you probably shouldn't use that variable like that. You can also force `v` to be block-local like this

```ruby
  threads << Thread.new do |;v|
    ...
```

**Comment by vemv** [comment]
> Is v defined somewhere else in this code, outside of the block? 

No, it isn't! Here's the class (a few commits later), which is pretty small. https://gist.github.com/vemv/7f826a0148ce3e3e49c0dea8440d2458

`v` is local and clear there.

I still am able to reproduce the issue: the version with `v` is consistently correct (always the same, correct result), and the version without `v` is inconsistent and incorrect (doesn't even give me the same incorrect result every time!).

**Comment by pitr-ch** [comment]
@vemv thanks for sharing the problem with us! What Ruby and version do you run?

**Comment by vemv** [comment]
Hey there Petr!

I use MRI: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]`

**Comment by thedarkone** [comment]
@vemv what do you mean by "I would get totally different results"? Your code is non-deterministic (due to threading), you should be getting different results pretty much every run.

Are you experiencing "lost results", where some transactions are not appended to the `transactions` array (or the `result` array in the gist)? If so, then this is because `+=` is not atomic: `foo += bar` is a syntactic sugar for `foo = foo + bar`.

What you want is to use `Concurrent::Array#concat`, like this:

```ruby
transactions.concat(get_transactions(dates.min, dates.max))
```

Does this fix your issue?

**Comment by pitr-ch** [comment]
@thedarkone thanks! I've missed the `+=` usage.

**Comment by vemv** [comment]
Sounds like that's the case. I'll check in detail and provide a more
detailed reply when I have the time.

I guess it's not possible to override `+=`? That'd prevent my mistake.
Actually I was actively assuming that the Concurrent::Array implementation
did override `+=`.

**Comment by chrisseaton** [comment]
> I guess it's not possible to override `+=`?

In Python I think it is, but not in Ruby. I believe it's been suggested and rejected for Ruby before. There's no way for us to detect it's being done either so we can't even warn, unless we warned for all use of `#+`. Maybe we should do that for concurrent array?

**Comment by pitr-ch** [comment]
We would get false warnings for legitimate uses of `#+` though :/ 
- [ ] I think we should add warning to documentation though.

**Comment by chrisseaton** [comment]
I think if someone is explicitly using a concurrent array then warning them not to use `#+` could be reasonable.

**Comment by pitr-ch** [comment]
If user wants to just create third `Concurrent::Array` which is a concatenation of 2 other `Concurrent::Array`s then (since `Concurrent::Array` has same API as `::Array`) user should use `#+`. In this case the user would get warning even though the usage is fine. `#+` does not have an alias so he would have to either use `dup.concat` or we would have to introduce an alias for `#+` to be able to avoid the warning. By adding the warning we may wrongly assume that the above is not used, therefore I would rather just add warning to the documentation, since we cannot detect `+=` as it was mentioned.
