### ISSUE TITLE
Custom Fallback Policies for ThreadPoolExecutor

### ISSUE THREAD

**Issue by thedrow** [ruby-concurrency/concurrent-ruby#618]
We would like to instrument when the fallback policy is being used.
Unfortunately `handle_fallback` is private which doesn't allow us to add more behaviour.
Can we make it protected please?

**Comment by pitr-ch** [comment]
Unfortunately it looks like it is more complicated than just making it protected. The policies are implemented in Java https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/RejectedExecutionHandler.html for JavaExecutorService. The API has to match for both Java and Ruby executor. If you can contribute a PR, we will appreciate it. Otherwise we will get to it later.

**Comment by pitr-ch** [comment]
A solution could be to write a general JRuby RejectedExecutionHandler which would run a Ruby block when applied.

**Comment by chrisseaton** [comment]
@thedrow are you still interested in this feature?

**Comment by thedrow** [comment]
I no longer use Ruby so no.
