### ISSUE TITLE
Where is Concurrent::Set?

### ISSUE THREAD

**Issue by yegor256** [ruby-concurrency/concurrent-ruby#730]
Documentation link is broken and the class is not present in the package (if I'm not wrong). Where is it?

**Comment by pitr-ch** [comment]
Could you point me to the broken documentation? The Set is on master, but not yet released. It'll be in the next one.

**Comment by pitr-ch** [comment]
Ah the readme does not match the latest release but master. Unfortunately I have to keep the default branch master (whose readme is shown on https://github.com/ruby-concurrency/concurrent-ruby url) because it's the default base of all PRs and changing it would make contributions more difficult. Not sure there is anything practical I can do about it.

**Comment by jdantonio** [comment]
You could release a new version of the gem. Bump the minor version number.

**Comment by pitr-ch** [comment]
I've at least added a note at the begging of https://github.com/ruby-concurrency/concurrent-ruby/blob/master/README.md#features--documentation

**Comment by pitr-ch** [comment]
@jdantonio yeah a new version is my primary focus. I am still fighting CI stability issues but I am getting there. A new release will be out soon.
