### ISSUE TITLE
Concurrent::Future vs Concurrent::Promises::Future

### ISSUE THREAD

**Issue by fzakaria** [ruby-concurrency/concurrent-ruby#848]
The fact that there are two Future classes -- the former in the title having much less capabilities seems very confusing.

Is there a historic reason for keeping the two ?
Can we just alias:

```ruby
Concurrent::Future = Concurrent::Promises::Future
```

**Comment by pitr-ch** [comment]
yeah it is confusing. The old one has to stay for compatibility though. We have to be careful when trying to change any of the old APIs because this gem is the 20th most downloaded gem and about 1/5 of all gems depend transitively on it. The new implementation is not compatible with the old so it cannot replace it (although, I wish to do that).  However, we could be more "aggressive" with deprecation warnings, I think right now the deprecation is only documented.

**Comment by fzakaria** [comment]
I see. 
I haven't looked to detailed into the API but there's definitely some overlap. 
There might be the opportunity to move the implementation into a single class and just alias the constant name. 

(The method implementation could carry the deprecation warning)

We can close this then.
