### ISSUE TITLE
RubyMine integration fails due to custom gem require path

### ISSUE THREAD

**Issue by wjordan** [ruby-concurrency/concurrent-ruby#873]
Feel free to close this as 'not a bug', but I thought I'd raise awareness of a RubyMine IDE integration issue I stumbled upon affecting consumers of this dependency: [`RUBY-23350`](https://youtrack.jetbrains.com/issue/RUBY-23350).

The root cause of the issue seems to be that the `concurrent-ruby` gem uses a non-standard require path: https://github.com/ruby-concurrency/concurrent-ruby/blob/7dc6eb04142f008ffa79a59c125669c6fcbb85a8/concurrent-ruby.gemspec#L23

Unfortunately, due to the issue linked above the RubyMine IDE currently does not index these non-standard paths correctly, causing IDE features such as code completion, jump to class definition and quick documentation to not work with this library: 
<img src=https://user-images.githubusercontent.com/56541/86153444-88ca6080-bab6-11ea-998b-c942a607dde8.png width=200/>

Obviously it would be great if JetBrains quickly fixed this issue on their end, but this could also be worked around in this gem if the built gem's directory structure was changed to the default `lib` require path. I ~would be happy to attempt~ opened a PR along these lines, please let me know if you would be open to such a change.

Otherwise, I would encourage anyone affected by this issue to encourage JetBrains to update their IDE to prioritize a fix for this bug (e.g., by up-voting the linked issue).

**Comment by pitr-ch** [comment]
This is really a bad problem :( For context it was moved because of packaging issues see #812
Thanks for the PR! I have to think what to do about this. 
Best approach probably is merging edge into core which will allow common load paths for both. It has to be done with care though, to keep it backward compatible (hopefully it will be possible).
@wjordan It is quite a task, would you be willing to try?

**Comment by eregon** [comment]
I managed to set up IntelliJ/RubyMine manually as documented in https://github.com/ruby-concurrency/concurrent-ruby/commit/8b2d2482475c2cb78ff9b7ee140f24782aa54f73.
It requires a few manual steps but then works well.

I'm not a fan of non-standard require_paths, but OTOH we need to have edge files somewhere (or deprecate/merging concurrent-edge but that's a big undertaking).

I would personally have refused that a system package imposes the layout (#812), but now that it's changed, it seems high effort and trouble to change it again.

I'm marking this as fixed since there is a documented way to make it work without changing the whole structure again.
