### ISSUE TITLE
STM guarantees clarification

### ISSUE THREAD

**Issue by pitr-ch** [ruby-concurrency/concurrent-ruby#887]
The current implementation seems to allow https://en.wikipedia.org/wiki/Software_transactional_memory#Implementation_issues
see the example below. I think it should be clarified in the readme.

```ruby
require 'concurrent-ruby'

v1 = Concurrent::TVar.new(0)
v2 = Concurrent::TVar.new(0)

2.times.map{
   Thread.new{
     while true
       Concurrent::atomically do
         t1 = v1.value
         t2 = v2.value
         raise [t1, t2].inspect if t1 != t2
       end
     end
   }

   Thread.new{
     100_000.times{|i|
       Concurrent::atomically do
         v1.value += 1
         v2.value += 1
       end
     }
   }
}.each{|t| p t.join}

__END__

$ ~/tmp/jruby-9.2.13.0/bin/jruby -v ~/whome/src/rb/t.rb
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM
11.0.8+10-post-Ubuntu-0ubuntu120.04 on
11.0.8+10-post-Ubuntu-0ubuntu120.04 +jit [linux-x86_64]
warning: thread "Ruby-0-Thread-3: /home/ko1/whome/src/rb/t.rb:1"
terminated with exception (report_on_exception is true):
RuntimeError: [8, 9]
   /home/ko1/whome/src/rb/t.rb at /home/ko1/whome/src/rb/t.rb:12
                    atomically at
/home/ko1/tmp/jruby-9.2.13.0/lib/ruby/gems/shared/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/tvar.rb:118
                          loop at org/jruby/RubyKernel.java:1442
                    atomically at
/home/ko1/tmp/jruby-9.2.13.0/lib/ruby/gems/shared/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/tvar.rb:108
   /home/ko1/whome/src/rb/t.rb at /home/ko1/whome/src/rb/t.rb:9
```

@chrisseaton would you have some time to do that?

**Comment by pitr-ch** [comment]
The transaction's `#commit` allows the partial reads of the values.

**Comment by chrisseaton** [comment]
Yes this is a weaker variant of STM. The implementation technique is described at https://github.com/ruby-concurrency/concurrent-ruby/blob/63a690770cebb836d0c66c3022327d5399f8894e/docs-source/tvar.md but maybe I need to break down and list the properties in a way that's more accessible.

**Comment by pitr-ch** [comment]
The doc mentions "and isolated - atomic blocks never interfere with each other when they are running" though. I think that could be interpreted as prohibiting the behaviour in the example.

**Comment by chrisseaton** [comment]
Yeah I'll take a fresh look and probably implement a stronger algorithm.

**Comment by pitr-ch** [comment]
That would be awesome 👍 Thanks.

**Comment by ko1** [comment]
👍

**Comment by ko1** [comment]
Just for clarification.

```ruby
require 'concurrent-ruby'

v1 = Concurrent::TVar.new(0)
v2 = Concurrent::TVar.new(0)

# monitor
  Thread.new{
    while true
      a = Concurrent::atomically do
         [v1.value,
         v2.value]
      end
      if a[0] != a[1]
        p a
        exit!
      end
    end
  }


# modifier
  Thread.new{
    100_000.times{|i|
      Concurrent::atomically do
        v1.value += 1
        v2.value += 1
      end
    }
  }.join
```

On this example, the monitor detects inconsistency, and it is intentional, right?
I think it is possible that inconsistency *only* in `atomically` block (and if there is an inconsistency, the `atomically` abort and retry. However, this example shows it is inconsistency outside of `atomically`.

**Comment by chrisseaton** [comment]
Referring back to [1],

> The basic versions of these STMs allow a transaction to experience a conflict and to continue executing as a zombie; consequently, they do not provide opacity.

[1] T. Harris, J. Larus, and R. Rajwar. Transactional Memory. Morgan & Claypool, second edition, 2010.

So that's the technical term from what we're experiencing - a lack of 'opacity'.

Does that make sense to people - I will document that if it does.

I'd love to provide a full library of STMs for Ruby with different characteristics (I did half my PhD on STM before I switched to Ruby) but don't really have the time.

**Comment by pitr-ch** [comment]
Could you include an example? And maybe provide some advice to users how to avoid these issues?

**Comment by ko1** [comment]
My understanding of "Opacity" is, reading inconsistent values in a *transaction*, and the transaction should be abort at commit time if there is inconsistent reading.

The example https://github.com/ruby-concurrency/concurrent-ruby/issues/887#issuecomment-696177282 is inconsistency out of transaction.

I'm not an expert of STM, so I can be wrong.

**Comment by chrisseaton** [comment]
> The example #887 (comment) is inconsistency out of transaction.

Not sure what you mean, sorry - it's inside a transaction - an `atomically` block.

Do you mean it's visible outside of the transaction? Yes its allowed to escape due to you throwing a transaction. Throwing an exception from inside the transaction is like a side effect and allows you to leak information out of it. We don't disallow exceptions though, because we think it would become very hard to debug errors if we did this.

The inconsistent transaction isn't *committed* which is the important thing.

Stronger (and less performant) transaction implementations can avoid these zombie transactions.

**Comment by ko1** [comment]
> Do you mean it's visible outside of the transaction? Yes its allowed to escape due to you throwing a transaction.

The following code doesn't throw any exceptions.
But it returns values of v1 and v2.

```
      a = Concurrent::atomically do
         [v1.value,
         v2.value]
      end
```

In `atomically` block, missing opacity can allow reading v1 and v2 values inconsistently (in this case, allowing `v1 != v2`). However, the return array should contains consistent v1 and v2 values (in this case `v1 == v2`) on STM I think.

In other words, I think STM should check consistency of v1 and v2 versions at the commit time. No?

**Comment by ko1** [comment]
Note that I don't want to discuss about the concurrent-ruby's behavior, but I want to know the word "Opacity" and STM's expected features.

**Comment by chrisseaton** [comment]
Ah - I think this might be because your transaction is read-only, so might be omitting the commit check. Read-only transactions aren't usual which is why there could be a bug here. I'll look into it.

'Opacity' was introduced in

> Rachid Guerraoui and Michał Kapałka. On the correctness of transactional memory. In
PPoPP ’08: Proc. 13th ACM SIGPLAN Symposium on Principles and Practice of Parallel Pro- gramming, pages 175–184, February 2008.

https://www.cse.msu.edu/~cse914/Readings/onCorrectnessOfTransactionalMemory-ppopp08.pdf

It means:

> the additional requirement that even non-committed transactions are prevented from accessing inconsistent states

**Comment by ko1** [comment]
Thank you so much!

So maybe current behavior is a bug, and my understanding of Opacity was correct.

**Comment by chrisseaton** [comment]
I think this illustrates the problem now:

```ruby
require 'concurrent-ruby'

v1 = Concurrent::TVar.new(0)
v2 = Concurrent::TVar.new(0)

Thread.new do
  loop do
    a = Concurrent::atomically do
      a = v1.value
      b = v2.value

      # comment out these two lines and you do get failures - leave in and you don't
      v1.value += 1
      v2.value += 1

      [a, b]
    end
    raise if a[0] != a[1]
  end
end

loop do
  Concurrent::atomically do
    v1.value += 1
    v2.value += 1
  end
end
```

**Comment by pitr-ch** [comment]
Note: any write will fix the problem having e.g. `v3.value = 1` instead of `v1.value += 1; v2.value += 1` will also force the transaction abort.
